#  _    _  ___   ___ ______ 
# | |  | |/ _ \ / _ \| ___ \
# | |  | | (_) | (_) | |_/ /
# | |/\| |\___/ \___/|  __/ 
# \  /\  /           | |    
#  \/  \/            \_|  
#
# This is the main configuration file for the woop
# renderer! All options (and their defaults) are
# listed below.

# These values are required!
[general]
wad = "path/to/your/wad"
level = "LEVELNAME"

[player]
# How tall the player is
height = 45.0
# How much acceleration to apply when the player is
# falling
gravity = 9800.0
# How fast the camera should rotate
sensitivity = 1.0
# Maximum movement speed
move_speed = 300.0
# How fast the player accelerates
acceleration = 900.0
# How much drag to apply when no input is pressed
drag = 0.1
# Whether mouse aiming is enabled
enable_mouse = true
# Whether flight is enabled
enable_flight = false

[window]
# Title of the window
title = "Woop"
# Size of the window
size = [2560, 1440]
# Whether the window should be fullscreen
fullscreen = false
# Whether the window should be resizable
resizable = true
# Whether the window should be decorated
decorated = true

[camera]
# Near clipping plane
near_plane = 0.1
# Far clipping plane
far_plane = 10000.0
# Field of view
fov = 90.0

[renderer]
# Path to the vertex shader used to render the 
# output image
vertex_shader = "assets/shaders/vert.glsl"
# Path to the fragment shader used to render the 
# output iamge
fragment_shader = "assets/shaders/frag.glsl"
# Resolution of the output image. Be wary of
# performance when increasing this.
resolution = [320, 200]
# Color used to clear the screen
clear_color = [0, 0, 0]
# Color of fog in the level
fog_color = [0, 0, 0]
# Strength of fog in the level. Set to 0 to 
# disable.
fog_strength = 0.75
